name: API Snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: OSSRH_USER
          server-password: OSSRH_PASS

      - name: Build with Maven
        run: mvn -B -pl API package

      - name: Publish to OSSRH
        run: mvn -B -pl API deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
