
name: Eval features

on:
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: do-it-echo
        run: echo "Hello ${{ github.workspace }}"
