
name: Eval features

on:
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: New File
        run: |
          echo "Some test" >${{ github.workspace }}/Support/test.txt
          ls -l ${{ github.workspace }}/Support