name: IDE Snapshot

on: 
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    
    - name: Build with Maven
      run: mvn -B -pl IDE -P complete-mac-jar package
      
    - name: Check build
      run: ls -l ${{ github.workspace }}/IDE/target

#    - name: Publish to OSSRH
#      run: mvn -B -pl API deploy
#      env:
#        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
#        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
