name: IDE Snapshot

on: 
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    
    - name: Build with Maven
      run: mvn -B -pl IDE -P complete-mac-jar package | egrep -v "^\[INFO\].*?Download.*?http"
      
    - name: Remove thin jar
      run: rm ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT.jar
      
    - name: Rename fat jar
      run: mv ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT-complete-mac.jar ${{ github.workspace }}/IDE/target/sikulixmac-2.1.0-SNAPSHOT.jar

    - name: Publish to OSSRH
      run: >
        mvn -B -e deploy:deploy-file
            -Dfile='${{ github.workspace }}/IDE/target/sikulixmac-2.1.0-SNAPSHOT.jar'
            -Dpackaging=jar -DgroupId=com.sikulix -DartifactId=sikulixmac -Dversion=2.1.0-SNAPSHOT
            -DrepositoryId='ossrh -Durl=https://s01.oss.sonatype.org/content/repositories/snapshots/'
            | egrep -v "^\[INFO\].*?Download.*?http"
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}

    - name: check
      if: ${{ always() }}
      run: cat ${{ github.workspace }}/../../../.m2/settings.xml

